executables:
  pitanga:
    source-dirs: src
    main: Main.main
license-file: LICENSE
build-type: Simple
maintainer: Chris Stryczynski
dependencies:
- base >=4.11 && <4.15
- turtle
- aeson-pretty
- strings
- rainbow
- lens
- aeson
- bytestring
- split
- text
- time >= 1.9.2
- old-locale
- directory
- pretty-simple
- string-conversions
- optparse-applicative
- vector
- attoparsec
name: platinumpitanga
version: '1.0.0.0'
extra-source-files: ChangeLog.md
author: Chris Stryczynski
license: BSD3
default-extensions: 
  - LambdaCase
library:
  source-dirs: src
