source-dirs: src
executables:
  pitanga:
    main: Main.main
license-file: LICENSE
build-type: Simple
maintainer: Chris Stryczynski
dependencies:
- base >=4.11 && <4.12
- turtle
- aeson-pretty
- strings
- rainbow
- lens
- aeson
- bytestring
- split
- text
- time
- old-locale
- directory
- pretty-simple
- string-conversions
- optparse-applicative
- vector
name: app
version: '0.1.0.0'
extra-source-files: ChangeLog.md
author: Chris Stryczynski
license: BSD3
default-extensions: 
  - LambdaCase
