source-dirs: src
executables:
  pitangaStartTask:
    main: Main.startLog
  pitangaStopTask:
    main: StopTask.main
  pitangaResumeTask:
    main: ResumeTask.resumeTask
  pitangaLog:
    main: Log.showLog
  pitangaExport:
    main: Export.main
license-file: LICENSE
build-type: Simple
maintainer: Chris Stryczynski
dependencies:
- base >=4.11 && <4.12
- turtle
- aeson-pretty
# common
- rainbow
- lens
- aeson
- bytestring
- stm
- split
- text
- time
- thyme
- binary
- binary-orphans
- old-locale
- directory
- pretty-simple
- string-conversions
- optparse-applicative
name: app
version: '0.1.0.0'
extra-source-files: ChangeLog.md
author: Chris Stryczynski
license: BSD3
default-extensions: 
  - LambdaCase
